### ISSUE TITLE
Script makes assumptions which are not evident and undocumented; what is supposed to be mounted where?

### ISSUE THREAD

**Issue by emk2203** [TheLillo/generate-image-hc4-armbian#2]
As the title says; script and docs are unclear what the starting point is, what needs to be mounted where etc.

Running the script from some directory in `/home/user` fails after a while.

**Comment by TheLillo** [comment]
Hi there!  Thanks for reaching out and bringing this to our attention.

We appreciate your feedback on the clarity of the script and documentation. Our project is indeed open to contributions, and we would welcome your help in improving both the documentation and the script. Collaborative efforts like yours are what make open source projects thrive!

If you're interested in contributing, feel free to fork the project make changes to address the issues you've encountered and submit a pull request. Any enhancements to the documentation or script will benefit the entire community. Remember, open source is a collective effort, and your contributions can make a significant impact.

Additionally, it's worth noting that the script may be encountering issues because the expected uImage is not present inside the boot folder of the Armbian Image.  I'm doing some tests

Feel free to submit a pull request with your changes or open further discussions if you have more questions. Let's work together to enhance the project and make it even more accessible for everyone. Thanks again for your engagement in the open source spirit!

**Comment by TheLillo** [comment]
Well, can you confirm that now it works for you? I pushed new version of the script

**Comment by emk2203** [comment]
The script still complains that `/mnt` is not mounted and that no mount point is given for `/tmp/odroid`, but it runs through successfully(?):

```
umount: /mnt: nicht eingehängt.
umount: /tmp/odroid: kein Einhängepunkt angegeben.
--2023-11-18 19:27:51--  https://redirect.armbian.com/region/EU/odroidhc4/Jammy_current
Auflösen des Hostnamens redirect.armbian.com (redirect.armbian.com) … 130.185.239.78, 2602:fea7:e0d:1001::12
Verbindungsaufbau zu redirect.armbian.com (redirect.armbian.com)|130.185.239.78|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 302 Found
Platz: https://mirrors.netix.net/armbian/dl/odroidhc4/archive/Armbian_23.8.1_Odroidhc4_jammy_current_6.1.50.img.xz [folgend]
--2023-11-18 19:27:52--  https://mirrors.netix.net/armbian/dl/odroidhc4/archive/Armbian_23.8.1_Odroidhc4_jammy_current_6.1.50.img.xz
Auflösen des Hostnamens mirrors.netix.net (mirrors.netix.net) … 87.121.121.2, 2a00:1728:20::2
Verbindungsaufbau zu mirrors.netix.net (mirrors.netix.net)|87.121.121.2|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 605342264 (577M) [application/x-xz]
Wird in ‘Jammy_current.xz’ gespeichert.
Jammy_current.xz                                    100%[================================================================================================================>] 577,30M  12,8MB/s    in 57s     

2023-11-18 19:28:50 (10,1 MB/s) - ‘Jammy_current.xz’ gespeichert [605342264/605342264]

'zz-update-boot-images' -> '/mnt/etc/kernel/postinst.d/zz-update-boot-images'
'fancontrol' -> '/mnt/etc/fancontrol'
0+0 Datensätze ein
0+0 Datensätze aus
0 Bytes kopiert, 0,000151032 s, 0,0 kB/s
Es wird überprüft, ob diese Festplatte zur Zeit benutzt wird … OK

Festplatte odroid-hc4.img: 2,47 GiB, 2654994432 Bytes, 5185536 Sektoren
Einheiten: Sektoren von 1 * 512 = 512 Bytes
Sektorgröße (logisch/physikalisch): 512 Bytes / 512 Bytes
E/A-Größe (minimal/optimal): 512 Bytes / 512 Bytes

>>> Skript-Header wurde akzeptiert.
>>> Skript-Header wurde akzeptiert.
>>> Skript-Header wurde akzeptiert.
>>> Skript-Header wurde akzeptiert.
>>> Skript-Header wurde akzeptiert.
>>> Created a new DOS (MBR) disklabel with disk identifier 0x03823826.
odroid-hc4.img1: Eine neue Partition 1 des Typs „W95 FAT32 (LBA)“ und der Größe 128 MiB wurde erstellt.
odroid-hc4.img2: Eine neue Partition 2 des Typs „Linux“ und der Größe 1,8 GiB wurde erstellt.
odroid-hc4.img3: Fertig.

Neue Aufteilung:
Festplattenbezeichnungstyp: dos
Festplattenbezeichner: 0x03823826

Gerät           Boot Anfang    Ende Sektoren Größe Kn Typ
odroid-hc4.img1        2048  264191   262144  128M  c W95 FAT32 (LBA)
odroid-hc4.img2      264192 4139007  3874816  1,8G 83 Linux

Die Partitionstabelle wurde verändert.
Festplatten werden synchronisiert.
mkfs.fat 4.2 (2021-01-31)
3874816+0 Datensätze ein
3874816+0 Datensätze aus
1983905792 Bytes (2,0 GB, 1,8 GiB) kopiert, 16,255 s, 122 MB/s
[+] DONE
umount: /mnt: nicht eingehängt.
umount: /tmp/odroid: nicht eingehängt.
```
I don't have access to the Odroid HC4 at the moment, so I cannot test it out on the real hardware. I can see that the image is 131072000 bytes bigger than the downloaded, uncompressed Armbian original, so the script has definitely done some modifications. Hoping to test this tomorrow, will give you more feedback then.

Still curious to know what should be done with `/mnt` and `/tmp/odroid`, though. Or is the error message just indicating that these are free to use for the script?

**Comment by TheLillo** [comment]
Hi,
The `[+] DONE` means that it worked. 
The script mount that folder in order to take from Armbian image some files and the script need to mount a file system to create the `ISO`. It's all in the script, you can use the command `man` to check the manpages so you can have a detail of the commands.
